variable "resource_group_name" {}
variable "location" {}
variable "vnet" {}
variable "websubnet" {}
variable "appsubnet" {}
variable "web_admin_username" {}
variable "web_admin_password" {}
variable "app_admin_username" {}
variable "app_admin_password" {}