variable "resource_group_name" {}
variable "location" {}
variable "vnetcidr" {}
variable "websubnetcidr" {}
variable "appsubnetcidr" {}
variable "web_admin_username" {}
variable "web_admin_password" {}
variable "app_admin_username" {}
variable "app_admin_password" {}