variable "resource_group_name" {}
variable "location" {}
variable "vnetcidr" {}
variable "websubnetcidr" {}
variable "appsubnetcidr" {}
variable "dbsubnetcidr" {}
variable "web_admin_username" {}
variable "web_admin_password" {}
variable "app_admin_username" {}
variable "app_admin_password" {}
variable "primary_database" {}
variable "administrator_login" {}
variable "administrator_login_password" {}